#!/usr/bin/env python3
import argparse
import datetime
from MeesmanScraper.scraper import WebScraper

parser = argparse.ArgumentParser()
parser.add_argument("--verbose", help="indicate if verbosian output is necessary", action='store_true')
args = parser.parse_args()

# Initialize Meesman scraper
MyMS = WebScraper(args.verbose)

# Run portefeuille table ETL
MyMS.etl_portefeuille_table()

print("ETL jobs are finished on {}".format(datetime.datetime.now()))